from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Protocol

from app.models.media import MediaLibrary
from app.models.preset import CompressionPreset
from app.models.queue import QueueJob
from app.models.tags import TagAssignment


class MediaRepository(Protocol):
    def get_library(self) -> MediaLibrary:
        ...


class PresetRepository(Protocol):
    def get_all(self) -> list[CompressionPreset]: ...

    def get_by_id(self, preset_id: str) -> CompressionPreset | None: ...

    def save(self, preset: CompressionPreset) -> None: ...

    def delete(self, preset_id: str) -> None: ...


class QueueRepository(Protocol):
    def get_all(self) -> list[QueueJob]: ...

    def add(self, job: QueueJob) -> None: ...

    def remove(self, job_id: str) -> None: ...

    def save(self, job: QueueJob) -> None: ...

    def transaction(self) -> AbstractContextManager[object]: ...


class TagRepository(Protocol):
    def get_many(self, keys: list[str]) -> dict[str, TagAssignment]: ...

    def get(self, key: str) -> TagAssignment | None: ...

    def save(self, key: str, assignment: TagAssignment) -> None: ...

    def transaction(self) -> AbstractContextManager[object]: ...
