"""Schema v2. Rare/adapter-specific facts remain JSON; identity and streams are indexed."""
SCHEMA = [
    '''CREATE TABLE media_items (media_id TEXT PRIMARY KEY, scope TEXT NOT NULL CHECK(scope IN ('movie','show')), UNIQUE(media_id,scope))''',
    '''CREATE TABLE observations (
        observation_id TEXT PRIMARY KEY, root_id TEXT NOT NULL, relative_path TEXT NOT NULL,
        media_id TEXT NOT NULL REFERENCES media_items(media_id), scope TEXT NOT NULL,
        filesystem_id TEXT, inode INTEGER, generation TEXT, size INTEGER NOT NULL CHECK(size>=0),
        mtime_ns INTEGER NOT NULL, ctime_ns INTEGER, hardlinks INTEGER,
        fingerprints TEXT NOT NULL, container TEXT, container_bitrate INTEGER, duration_seconds REAL, probe_metadata TEXT)''',
    '''CREATE TABLE library_files (
        file_id TEXT PRIMARY KEY, media_id TEXT NOT NULL REFERENCES media_items(media_id),
        scope TEXT NOT NULL, root_id TEXT NOT NULL, relative_path TEXT NOT NULL,
        revision_id TEXT NOT NULL REFERENCES file_revisions(revision_id) DEFERRABLE INITIALLY DEFERRED,
        observation_id TEXT NOT NULL REFERENCES observations(observation_id),
        presence TEXT NOT NULL CHECK(presence IN ('present','missing')), last_seen_sequence INTEGER NOT NULL,
        show_id TEXT,
        FOREIGN KEY(media_id,scope) REFERENCES media_items(media_id,scope),
        FOREIGN KEY(revision_id,file_id) REFERENCES file_revisions(revision_id,file_id) DEFERRABLE INITIALLY DEFERRED)''',
    '''CREATE TABLE file_revisions (
        revision_id TEXT PRIMARY KEY, file_id TEXT NOT NULL REFERENCES library_files(file_id) DEFERRABLE INITIALLY DEFERRED,
        observation_id TEXT NOT NULL REFERENCES observations(observation_id),
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(revision_id,file_id))''',
    '''CREATE TABLE streams (
        observation_id TEXT NOT NULL REFERENCES observations(observation_id) ON DELETE CASCADE,
        stream_index INTEGER NOT NULL, kind TEXT NOT NULL, codec TEXT NOT NULL,
        language TEXT, title TEXT, bitrate INTEGER, width INTEGER, height INTEGER, resolution_class INTEGER,
        scan_type TEXT NOT NULL, field_order TEXT, frame_rate TEXT, pixel_format TEXT,
        channels INTEGER, channel_layout TEXT, sample_rate INTEGER,
        dispositions TEXT NOT NULL, hdr TEXT, metadata TEXT NOT NULL,
        bit_depth INTEGER, color_primaries TEXT, color_transfer TEXT, color_matrix TEXT,
        PRIMARY KEY(observation_id, stream_index))''',
    '''CREATE TABLE chapters (
        observation_id TEXT NOT NULL REFERENCES observations(observation_id) ON DELETE CASCADE,
        ordinal INTEGER NOT NULL, payload TEXT NOT NULL, PRIMARY KEY(observation_id,ordinal))''',
    '''CREATE TABLE scan_runs (root_id TEXT NOT NULL, sequence INTEGER NOT NULL,
        status TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY(root_id,sequence))''',
    '''CREATE TABLE reconciliation_issues (root_id TEXT NOT NULL, sequence INTEGER NOT NULL,
        ordinal INTEGER NOT NULL, path TEXT NOT NULL, reason TEXT NOT NULL,
        fingerprint_needed TEXT, candidate_file_ids TEXT NOT NULL,
        PRIMARY KEY(root_id,sequence,ordinal), FOREIGN KEY(root_id,sequence) REFERENCES scan_runs(root_id,sequence))''',
    '''CREATE TABLE artifacts (
        artifact_id TEXT PRIMARY KEY, job_id TEXT NOT NULL UNIQUE,
        file_id TEXT NOT NULL REFERENCES library_files(file_id),
        revision_id TEXT NOT NULL REFERENCES file_revisions(revision_id),
        root_id TEXT NOT NULL, relative_path TEXT NOT NULL,
        preset TEXT NOT NULL, mode TEXT NOT NULL, status TEXT NOT NULL,
        UNIQUE(root_id,relative_path), FOREIGN KEY(revision_id,file_id) REFERENCES file_revisions(revision_id,file_id))''',
    'CREATE UNIQUE INDEX present_path ON library_files(root_id,relative_path) WHERE presence=\'present\'',
    'CREATE INDEX file_path ON library_files(root_id,relative_path)',
    'CREATE INDEX file_media ON library_files(media_id)',
    'CREATE INDEX file_root_presence ON library_files(root_id,presence,scope)',
    'CREATE INDEX file_show ON library_files(show_id,presence)',
    'CREATE INDEX revision_file ON file_revisions(file_id)',
    'CREATE INDEX current_revision ON library_files(revision_id)',
    'CREATE INDEX media_scope ON media_items(scope)',
    'CREATE INDEX physical_identity ON observations(root_id,filesystem_id,inode,generation)',
    'CREATE INDEX relocation_evidence ON observations(root_id,media_id,size)',
    'CREATE INDEX artifact_source ON artifacts(file_id,revision_id)',
    'CREATE INDEX stream_kind ON streams(kind,codec)',
]
